fix pick commit 8ae06fbf8
- build stop ?

....../cdk/build_source/neutrino-mp-fs/src/gui/components/cc_item.cpp: In member function 'void CComponentsItem::paintInit(bool)':

....../cdk/build_source/neutrino-mp-fs/src/gui/components/cc_item.cpp:199:174: error: request for member 'id' in '((CComponentsItem*)this)->CComponentsItem::cc_item_type', which is of non-class type 'int'
  dprintf(DEBUG_DEBUG, "\033[1;32m[CComponentsItem]\t[%s - %d], init and paint item type = %d  [%s]...\033[0m\n", __func__, __LINE__, cc_item_type.id, cc_item_type.name.c_str());
                                                                                                                                                                              ^
....../cdk/build_source/neutrino-mp-fs/src/gui/components/cc_item.cpp:199:191: error: request for member 'name' in '((CComponentsItem*)this)->CComponentsItem::cc_item_type', which is of non-class type 'int'
  dprintf(DEBUG_DEBUG, "\033[1;32m[CComponentsItem]\t[%s - %d], init and paint item type = %d  [%s]...\033[0m\n", __func__, __LINE__, cc_item_type.id, cc_item_type.name.c_str());

- see here https://github.com/fs-basis/neutrino-mp-fs/commit/8ae06fbf8b0af58f01c897618940d1e93956be6e#diff-3defc8bbb4251a0f8c1b6ae837ef574fR199